### ISSUE TITLE
Unable to find a valid access token. Please login

### ISSUE THREAD

**Issue by markcs** [fonoster/routr-ctl#8]
I can't seem to run rctl.  I keep getting the following errors:

$ rctl get gateway
Unable to find a valid access token. Please login

routr is running:

:/snap/rctl/current$ ps -ef|grep routr
root      893650       1  0 23:00 ?        00:00:00 /bin/bash /snap/routr-server/25/start.sh
root      893696  893650  0 23:00 ?        00:00:00 sh /snap/routr-server/25/routr
root      893699  893696  1 23:00 ?        00:00:10 /snap/routr-server/25/usr/lib/jvm/java-8-openjdk-amd64/bin/java -DDATA=/snap/routr-server/25 -Dlog4j.configurationFile=config/log4j2.yml -Dgraal.TruffleFunctionInlining=false -Dgraal.CompilationFailureAction=Silent -Dpolyglot.js.experimental-foreign-object-prototype=true -Dpolyglot.js.nashorn-compat=true -Dnashorn.args=--no-deprecation-warning -classpath /snap/routr-server/25/libs/* io.routr.core.Launcher

**Comment by psanders** [comment]
You must login to you Routr instance, before you send any commands. It look something like this:

`rctl login https://localhost:4567/api/v1beta1 -u admin -p changeit`

For more about `rctl` check out the [npm package](https://www.npmjs.com/package/routr-ctl) site

> Don't forget to change localhost if you are running Routr on a different station

**Comment by psanders** [comment]
I'm closing this issue. Please feel free to re-open if the problem persist.
